fetch-data:
	mkdir -p ./data
	curl -o ./data/heic0611b_6200.tif https://esahubble.org/media/archives/images/original/heic0611b.tif
	curl -o ./data/heic0611b_2048.jpg https://cdn.esahubble.org/archives/images/wallpaper5/heic0611b.jpg
	curl -o ./data/heic0611b_1024.jpg https://cdn.esahubble.org/archives/images/wallpaper1/heic0611b.jpg
